name: Partial test for Windows
on: [push, pull_request]
jobs:
  run_pytest:
    runs-on: windows-2019
    strategy:
      matrix:
        python_version: ["3.6", "3.7", "3.8"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{matrix.python_version}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Build irspack
        run: |
          pip install --upgrade pip
          python setup.py develop
      - name: Run pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=./irspack tests/
